/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminPack.vista;

import static AdminPack.vista.AdminGui.PanelAdminGuiPrincipal;
import static AdminPack.vista.Vent_List_paci.panelListPaciVent;
import static AdminPack.vista.Vent_citas.panelCitasVent;
import static AdminPack.vista.Vent_clientes.panelClientesVent;
import static AdminPack.vista.Vent_facturas.panelFacturasVent;
import static AdminPack.vista.Vent_histo_clinic.panelHistoClinicVent;
import static AdminPack.vista.Vent_home.panelHomeDesign;
import java.awt.BorderLayout;
import static AdminPack.vista.Vent_procedi.panelProcediVent;
import static AdminPack.vista.Vent_reportes.panelRepoVent;
import static AdminPack.vista.Vent_users.panelUsersVent;
import javax.swing.ImageIcon;



/**
 *
 * @author Andres
 */
public class Login extends javax.swing.JFrame {
    
   ImageIcon iconobtnNS = new ImageIcon("src/acme/Images/User_B.png");
   ImageIcon iconobtn2NS = new ImageIcon("src/acme/Images/Inicio_B.png");
   ImageIcon iconobtn3NS = new ImageIcon("src/acme/Images/Procedimientos_B.png");
   ImageIcon iconobtn4NS = new ImageIcon("src/acme/Images/Reportes_B.png");
   ImageIcon iconobtn5NS = new ImageIcon("src/acme/Images/Citas_B.png");
   ImageIcon iconobtn6NS = new ImageIcon("src/acme/Images/Clientes_B.png");
   ImageIcon iconobtn7NS = new ImageIcon("src/acme/Images/Facturas_B.png");
   ImageIcon iconobtn8NS = new ImageIcon("src/acme/Images/ListaPacientes_B.png");
   ImageIcon iconobtn9NS = new ImageIcon("src/acme/Images/HistoriasClinicas_B.png");

   ImageIcon iconobtn = new ImageIcon("src/acme/Images/User_B_Selected.png");
   ImageIcon iconobtn2 = new ImageIcon("src/acme/Images/Inicio_B_Selected.png");
   ImageIcon iconobtn3 = new ImageIcon("src/acme/Images/Procedimientos_B_Selected.png");
   ImageIcon iconobtn4 = new ImageIcon("src/acme/Images/Reportes_B_Selected.png");
   ImageIcon iconobtn5 = new ImageIcon("src/acme/Images/Citas_B_Selected.png");
   ImageIcon iconobtn6 = new ImageIcon("src/acme/Images/Clientes_B_Selected.png");
   ImageIcon iconobtn7 = new ImageIcon("src/acme/Images/Facturas_B_Selected.png");
   ImageIcon iconobtn8 = new ImageIcon("src/acme/Images/ListaPacientes_B_Selected.png");
   ImageIcon iconobtn9 = new ImageIcon("src/acme/Images/HistoriasClinicas_B_Selected.png");
    
    public Login() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        B_Agre_cita = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        PanelLoginPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelLoginPrincipal.setMaximumSize(new java.awt.Dimension(1233, 693));
        PanelLoginPrincipal.setMinimumSize(new java.awt.Dimension(1233, 693));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/DiseñoLateralLogin.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_Agre_cita.setBackground(new java.awt.Color(255, 255, 255));
        B_Agre_cita.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        B_Agre_cita.setForeground(new java.awt.Color(255, 255, 255));
        B_Agre_cita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/BotonIngreasr.png"))); // NOI18N
        B_Agre_cita.setText("INGRESAR");
        B_Agre_cita.setBorderPainted(false);
        B_Agre_cita.setContentAreaFilled(false);
        B_Agre_cita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_Agre_cita.setFocusPainted(false);
        B_Agre_cita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        B_Agre_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Agre_citaActionPerformed(evt);
            }
        });
        jPanel2.add(B_Agre_cita, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 100));

        jTextField1.setBackground(new java.awt.Color(224, 224, 224));
        jTextField1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(104, 104, 104));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, 20));

        jTextField2.setBackground(new java.awt.Color(224, 224, 224));
        jTextField2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(104, 104, 104));
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/LogoLogin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/BarraUsuario.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/BarraPassword.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        botonX.setBackground(new java.awt.Color(255, 255, 255));
        botonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acme/Images/BotonEquis.png"))); // NOI18N
        botonX.setBorder(null);
        botonX.setBorderPainted(false);
        botonX.setContentAreaFilled(false);
        botonX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonX.setFocusPainted(false);
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginPrincipalLayout = new javax.swing.GroupLayout(PanelLoginPrincipal);
        PanelLoginPrincipal.setLayout(PanelLoginPrincipalLayout);
        PanelLoginPrincipalLayout.setHorizontalGroup(
            PanelLoginPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(201, 201, 201)
                .addGroup(PanelLoginPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginPrincipalLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(botonX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelLoginPrincipalLayout.setVerticalGroup(
            PanelLoginPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addGroup(PanelLoginPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(botonX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoginPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoginPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void B_Agre_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Agre_citaActionPerformed

        AdminGui ventanaAdmin = new AdminGui();
        ventanaAdmin.setSize(780, 570);
        ventanaAdmin.setLocation(30,60);
        
        PanelLoginPrincipal.removeAll();
        PanelLoginPrincipal.add(PanelAdminGuiPrincipal, BorderLayout.CENTER);
        PanelLoginPrincipal.revalidate();
        PanelLoginPrincipal.repaint();
    }//GEN-LAST:event_B_Agre_citaActionPerformed

    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed

        System.exit(0);
    }//GEN-LAST:event_botonXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Login LoginVent = new Login();
        LoginVent.setBounds(0, 0, 1233, 693);
        LoginVent.setVisible(true);
        LoginVent.setResizable(false);
        LoginVent.setLocationRelativeTo(null);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AdminGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agre_cita;
    private javax.swing.JPanel PanelLoginPrincipal;
    private javax.swing.JButton botonX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
